openedx/edx-drf-extensions

.travis.yml
MANIFEST.in
Makefile
edx_rest_framework_extensions/authentication.py
edx_rest_framework_extensions/tests/factories.py
edx_rest_framework_extensions/tests/test_authentication.py
pylintrc
pylintrc_tweaks
setup.py
test_requirements.txt
test_settings.py
tox.ini

Added authentication classes

---

edx_rest_framework_extensions/__init__.py
edx_rest_framework_extensions/permissions.py
edx_rest_framework_extensions/tests/test_permission.py
test_requirements.txt

Added IsSuperuser permission class

---

MANIFEST.in
edx_rest_framework_extensions/__init__.py
setup.cfg

- Removed unnecessary MANIFEST.in file
- Added setup.cfg to ensure we upload a single wheel to PyPI
ECOM-4221

Packaging updates 

---

docs/index.rst
docs/permissions.rst
setup.py

Added documentation for permissions module

---

docs/index.rst
docs/utils.rst
edx_rest_framework_extensions/tests/test_utils.py
edx_rest_framework_extensions/utils.py
setup.py
test_settings.py

Added jwt_decode_handler function

---

AUTHORS
docs/settings.rst
edx_rest_framework_extensions/__init__.py
edx_rest_framework_extensions/authentication.py
edx_rest_framework_extensions/settings.py
edx_rest_framework_extensions/tests/test_authentication.py

Add preferred_username JWTAuthentication

---

.travis.yml
edx_rest_framework_extensions/__init__.py
edx_rest_framework_extensions/authentication.py
setup.py
tox.ini

- Fixed issue with get_user_model()
- Added support for Django 1.10

Multiple Updates

---

codecov.yml
docs/settings.rst
edx_rest_framework_extensions/__init__.py
edx_rest_framework_extensions/utils.py

Verifying JWT audience claim by default

---

edx_rest_framework_extensions/__init__.py
edx_rest_framework_extensions/jwt_decoder.py
edx_rest_framework_extensions/settings.py
edx_rest_framework_extensions/tests/test_jwt_decoder.py
setup.py
test_requirements.txt
test_settings.py

While the [corresponding edx-platform PR](https://github.com/edx/edx-platform/pull/18629) updates the OAuth Provider to support Asymmetric JWTs, this PR updates the corresponding code for "OAuth2 Resource Providers" (i.e., REST endpoints).

Asymmetric JWT support

---

edx_rest_framework_extensions/__init__.py
edx_rest_framework_extensions/middleware.py
edx_rest_framework_extensions/tests/test_middleware.py
setup.py

I need to add tests.  However, you can review that this is a good start or not. :)

ARCH-198: Add RequestMetricsMiddleware.

---

AUTHORS
docs/index.rst
docs/middleware.rst
edx_rest_framework_extensions/__init__.py
edx_rest_framework_extensions/middleware.py

Add docs for RequestMetricsMiddleware.

---

edx_rest_framework_extensions/__init__.py
edx_rest_framework_extensions/auth/jwt/middleware.py
edx_rest_framework_extensions/auth/jwt/tests/test_middleware.py

**Related PR:** https://github.com/edx/frontend-auth/pull/5

Require clients to explicitly request JWT cookie authentication.

---

edx_rest_framework_extensions/__init__.py
edx_rest_framework_extensions/auth/jwt/authentication.py
edx_rest_framework_extensions/auth/jwt/cookies.py
edx_rest_framework_extensions/auth/jwt/tests/test_cookies.py

- Add call get_decoded_jwt_from_cookie
- Clean-up unused imports
ARCH-603

ARCH-603: decoded jwt from request

---

edx_rest_framework_extensions/__init__.py
edx_rest_framework_extensions/auth/jwt/authentication.py

Need this to help debug an issue with ecommerce e2e tests.

Log updated user attributes when using JWT auth.

---

edx_rest_framework_extensions/__init__.py
edx_rest_framework_extensions/auth/jwt/authentication.py

This will remove the temporary debug logging I added yesterday.

Remove logging of user attribute updates.

---

edx_rest_framework_extensions/__init__.py
edx_rest_framework_extensions/auth/jwt/middleware.py
edx_rest_framework_extensions/auth/jwt/tests/test_middleware.py

Update warning to info message as this case is handled automatically by the system

(PROD-505) Update warning to info

---

.gitignore
Makefile
edx_rest_framework_extensions/auth/jwt/authentication.py
edx_rest_framework_extensions/auth/jwt/decoder.py
edx_rest_framework_extensions/auth/jwt/tests/test_middleware.py
edx_rest_framework_extensions/paginators.py
requirements/base.in
requirements/base.txt
requirements/dev.txt
requirements/docs.in
requirements/docs.txt
requirements/pip-tools.txt
requirements/test.in
requirements/test.txt
tox.ini

Broken out from https://github.com/edx/edx-drf-extensions/pull/91 in order to commit the merge-conflict-susceptible code sooner than later.

Clean up pip-tools setup and stricten pylint

---

test_settings.py

Should have been removed in #101 , which removed nose.

Remove unused TEST_RUNNER setting

---

edx_rest_framework_extensions/auth/bearer/authentication.py
requirements/dev.txt
requirements/test.txt

We might soon be updating BearerAuthentiation(or removing). Adding these here to gauge where it is still actively used.

Added new relic metrics to bearerAuthentication

---

README.rst
edx_rest_framework_extensions/auth/README.rst
edx_rest_framework_extensions/auth/jwt/README.rst

* some documentation moved from edx-platform oauth_dispatch README.
* added relevant READMEs with more usage details.

enhance auth docs

---

edx_rest_framework_extensions/__init__.py
requirements/base.in
requirements/base.txt
requirements/dev.txt
requirements/docs.txt
requirements/pip-tools.txt
requirements/test.txt
tox.ini

Relevant JIRA : [https://openedx.atlassian.net/browse/BOM-1392](https://openedx.atlassian.net/browse/BOM-1392)

BOM-1392 : Loosen DRF constraint in edx-drf-extensions

---

edx_rest_framework_extensions/__init__.py
edx_rest_framework_extensions/auth/jwt/authentication.py
edx_rest_framework_extensions/auth/jwt/cookies.py
edx_rest_framework_extensions/auth/jwt/decoder.py
edx_rest_framework_extensions/auth/jwt/tests/test_decoder.py

See 3.0.1 fix PR here: https://github.com/edx/edx-drf-extensions/pull/116

ARCHBOM-1036: cherry-pick 3.0.1 fix on to 4.x

---

requirements/base.in
requirements/base.txt
requirements/dev.txt
requirements/test.txt
test_settings.py

See info in: https://openedx.atlassian.net/browse/BOM-1410

[BD] BOM-1410

---

edx_rest_framework_extensions/__init__.py

**Issue:** [BOM-1410](https://openedx.atlassian.net/browse/BOM-1410)
- Bumped the version to 5.0.1

BOM-1410 bumped the version to 5.0.1

---

edx_rest_framework_extensions/__init__.py

"Issue:" [BOM-1410](https://openedx.atlassian.net/browse/BOM-1410)
- Releasing new version tag `5.0.2` due to tag conflict. This version is the same as version `5.0.1`.

Bumped the version to 5.0.2

---

README.rst
openedx.yaml

- Update openedx.yaml
- Correct owner
- Mark OEP-18 noncompliance reason
- Fix insecure URLs

Ownership onboarding maintenance (30 days)

---

manage.py

removed deprecated `__future__` imports.
**JIRA:**
https://openedx.atlassian.net/browse/BOM-1797
**Reviewers:**
finished.

Removed deprecated future imports

---

README.rst

Adds a note to the README about including `csrf.urls`.
**JIRA:**
N/A
* **Dependencies:**: List dependencies on other outstanding PRs, issues, etc.
* **Merge deadline:** List merge deadline (if any)
* **Testing instructions:** Provide non-trivial testing instructions
* **Author concerns:** List any concerns about this PR
**Reviewers:**
finished.

Update README to include info about including csrf.urls

---

CHANGELOG.rst
edx_rest_framework_extensions/__init__.py
edx_rest_framework_extensions/middleware.py
edx_rest_framework_extensions/tests/factories.py
edx_rest_framework_extensions/tests/test_middleware.py

It's values can be `staff` or `superuser`.
Describe in a couple of sentences what this PR adds
**Reviewers:**
finished.

Add a new `request_is_staff_or_superuser` attribute.

---

requirements/base.txt
requirements/dev.txt
requirements/test.in
requirements/test.txt

Relevant JIRA : https://openedx.atlassian.net/browse/BOM-2255

BOM-2255 : Unpin packages causing make upgrade failures

---

docs/conf.py
requirements/base.txt
requirements/constraints.txt
requirements/dev.txt
requirements/docs.txt
requirements/pip-tools.txt
requirements/test.txt

**Issue:** [BOM-2544](https://openedx.atlassian.net/browse/BOM-2544)
- Added common constraints to fetch latest pinned versions which will resolve the failing [requirements upgrade build](https://build.testeng.edx.org/job/edx-drf-extensions-upgrade-python-requirements/36/).

BOM-2544: Add common constraints

---

README.rst

Correcting path to documentation

---

Makefile
edx_rest_framework_extensions/tests/test_permissions.py
requirements/base.txt
requirements/common_constraints.txt
requirements/dev.txt
requirements/docs.txt
requirements/pip-tools.txt
requirements/test.txt

Update pyjwt sed command to fix upgrade job.
**Reviewers:**
finished.

build: update pyjwt sed command to fix upgrade job

---

requirements/base.txt
requirements/common_constraints.txt
requirements/dev.txt
requirements/docs.txt
requirements/pip.in
requirements/pip.txt
requirements/test.txt

**Issue:** [BOM-3400](https://openedx.atlassian.net/browse/BOM-3400)
- Added `pip<22.1` constraint in the repo using common constraints.

fix: add pip<22.1 constraint

---

edx_rest_framework_extensions/auth/jwt/cookies.py
edx_rest_framework_extensions/auth/jwt/decoder.py

docs: Clarify docstrings for JWT "decoding" functions

---

.github/workflows/upgrade-python-requirements.yml
requirements/base.txt
requirements/dev.txt
requirements/docs.txt
requirements/test.txt

fixing a default branch in upgrade job
https://github.com/openedx/edx-drf-extensions/issues/281

build: fixing a default branch in upgrade job.

---

.github/workflows/pypi-publish.yml

Also, remove `user: __token__` since that's the default value.

build: Use maintained version of PyPI Publish action

---

CHANGELOG.rst
edx_rest_framework_extensions/auth/jwt/authentication.py
edx_rest_framework_extensions/auth/jwt/tests/test_middleware.py

Used monitoring to confirm a particular exception case is not happening, and removed it.

fix: remove unused exception case

---

edx_rest_framework_extensions/auth/jwt/decoder.py

Improved comments around issuer verification.

docs: improve comments for issuer verification

---

CHANGELOG.rst
edx_rest_framework_extensions/__init__.py
requirements/base.in
requirements/base.txt
requirements/dev.txt
requirements/test.txt

Followup from https://github.com/openedx/edx-drf-extensions/pull/311

feat: Drop pyjwkest dependency; fix version; update changelog

---

CHANGELOG.rst

See https://github.com/openedx/edx-drf-extensions/issues/346

docs: Add warning about 8.8.0 and malformed Base64 in YAML

---

tox.ini

The code coverage command mentioned in tox file is failing. The command has been updated in this PR.

fix: coverage issue

---

CHANGELOG.rst
requirements/base.in
requirements/base.txt
requirements/dev.txt
requirements/test.txt

**Summary:**
This pull request addresses the removal of the unused dependencies `six` and `python-dateutil` from the project. It's part of an ongoing research endeavor focusing on the identification and elimination of code bloat within software projects. 
**Rationale:**
The `six` dependency was intorduced on commit ec2b092 for its use on `edx_rest_framework_extensions/tests/test_paginators.py`. However, it was removed form the source code on 21f98ec, wghile still being declared as a direct dependency in the configuration files. 
Similarly, the `python-dateutil` dependency, was introduced in the project on b41a017 for its use on `edx_rest_framework_extensions/authentication.py`. However, it was removed on b9c2e61.
Removing these unused dependencies contributes to a leaner codebase, reduces …

Remove Unused Dependencies: six, python-dateutil 

---

CHANGELOG.rst
edx_rest_framework_extensions/__init__.py

**Description**
- Publish new version
**Related PR**
- https://github.com/openedx/edx-drf-extensions/pull/354

chore: publish new version

---

README.rst
docs/conf.py
requirements/base.txt
requirements/dev.txt
requirements/docs.in
requirements/docs.txt
requirements/test.txt

Also, add a link to the docs to the README.
https://github.com/openedx/edx-drf-extensions/issues/403

feat: Build docs with the correct stylesheet.
