edx_rest_framework_extensions/authentication.py
edx_rest_framework_extensions/tests/test_authentication.py
setup.py

BearerAuthentication has been updated to actually validate the expiration time of the access token response. This ensures that users with expired tokens are NOT authenticated.
ECOM-3895

Validating OAuth2 token expiration date

---

.travis.yml
edx_rest_framework_extensions/__init__.py

This ensures we deploy once, after a successful test build.
Fixes #2

Deploying to PyPI only from the Python 3.5, Django 1.9 build

---

edx_rest_framework_extensions/__init__.py
edx_rest_framework_extensions/authentication.py
edx_rest_framework_extensions/tests/test_authentication.py

If the username claim is missing from the JWT, the exception raised now includes a message stating this fact.
ECOM-4414

Updated JWT payload error handling

---

edx_rest_framework_extensions/__init__.py
edx_rest_framework_extensions/authentication.py
edx_rest_framework_extensions/settings.py
edx_rest_framework_extensions/tests/test_authentication.py

This mapping will allow consuming projects to specify which claims should be mapped to specific user model attributes. By default the email claim is mapped to the email attribute, and the administrator claim is mapped to the is_staff attribute.
ECOM-4793

Added support for JWT claim-user attribute mapping

---

edx_rest_framework_extensions/__init__.py
edx_rest_framework_extensions/settings.py
edx_rest_framework_extensions/tests/test_settings.py
edx_rest_framework_extensions/tests/test_utils.py
edx_rest_framework_extensions/utils.py
test_settings.py

@clintonb @mjfrey -- here's a first attempt at getting multiple issuers up and running -- it uses the nested for-loop approach, which we can certainly refactor, but I wanted to start from a working example instead of blazing a new trail since I'm not entirely familiar with JWT or this particular code project.

mattdrayer/multiple-jwt-issuers: Add support for multiple JWT issuers

---

edx_rest_framework_extensions/__init__.py
edx_rest_framework_extensions/tests/test_utils.py
edx_rest_framework_extensions/utils.py

@clintonb @douglashall @e0d -- added InvalidTokenError to the list of exceptions we watch for during JWT decoding.

mattdrayer/catch-token-exception: Also handle InvalidTokenError

---

edx_rest_framework_extensions/settings.py
edx_rest_framework_extensions/tests/test_settings.py

This line was causing test failures elsewhere in the edx-platform test suite, when warnings were appearing that shouldn't.
@clintonb @mattdrayer Do you know why this line is here? A library function like this shouldn't be changing the global warnings settings.
/cc @gsong

Don't change warnings global settings

---

codecov.yml
edx_rest_framework_extensions/paginators.py
edx_rest_framework_extensions/tests/test_paginators.py
setup.py

Pagination should be standard and easy across all of edx applications. By moving pagination into this package, it can be installed easily in other apps/projects

Moved paginators from edx-platform for easy reuse

---

AUTHORS
edx_rest_framework_extensions/__init__.py
setup.py
test_requirements.txt

Loosen a couple of restrictions on acceptable dependency versions in setup.py so the versions can be adjusted as needed in edx-platform.

PLAT-2065 Loosen version constraints in setup.py

---

openedx.yaml

This is only adding the openedx.yaml file that our bot uses to help manage OSPRs. Just for transparency, tests did not completely pass:
py27-django18: commands succeeded
py27-django19: commands succeeded
py27-django110: commands succeeded
py27-django111: commands succeeded
py35-django18: commands succeeded
py35-django19: commands succeeded
py35-django110: commands succeeded
py35-django111: commands succeeded
py36-django111: commands succeeded
ERROR:   quality: commands failed
docs: commands succeeded
Let me know if that is an issue.

adding openedx.yaml

---

edx_rest_framework_extensions/middleware.py
edx_rest_framework_extensions/permissions.py
edx_rest_framework_extensions/tests/test_middleware.py
edx_rest_framework_extensions/tests/test_permission.py
edx_rest_framework_extensions/utils.py

This PR introduces a Middleware as a [runway](http://www.scaledagileframework.com/architectural-runway/) for [enforcing OAuth scopes](https://github.com/edx/edx-platform/blob/master/openedx/core/djangoapps/oauth_dispatch/docs/decisions/0006-enforce-scopes-in-LMS-APIs.rst).
The Middleware updates any REST API views that use `JwtAuthentication` to always use the new JwtHasScope permission class.
This is needed because the Django framework doesn't allow us to configure `Permission` classes that *must* be enforced by all endpoints.  Although it supports a [DEFAULT_PERMISSION_CLASSES](http://www.django-rest-framework.org/api-guide/permissions/#setting-the-permission-policy) setting, any endpoint can choose to override and not use the defaults.  By having a middleware, we can update permission …

Middleware to ensure JwtHasScope permission for JWT Authentication

---

edx_rest_framework_extensions/__init__.py
edx_rest_framework_extensions/middleware.py
edx_rest_framework_extensions/tests/test_middleware.py
setup.py

EnsureJWTAuthSettingsMiddleware's check for permissions classes would
fail if it was applied to a view that uses conditional permissions from
the rest_condition library, like:
C(permissions.IsStaff) | permissions.IsUserInUrl
The cause of failure is that we were checking for subclasses of
particular permissions like IsStaff, and ConditionalPermissions are
outside of that hierarchy (and aren't even classes). This is one of the
contributing issues in ARCH-153.
This commit checks to see if a permission is a ConditionalPermission
and then expands it out so that we capture only the Permission classes
inside. So the check will pass as long as you have the required
permission class _somewhere_ in your view's permissions, with the
assumption being that if you're using the required permission in a …

Handle ConditionalPermission in middleware.

---

edx_rest_framework_extensions/__init__.py
edx_rest_framework_extensions/authentication.py
edx_rest_framework_extensions/config.py
edx_rest_framework_extensions/jwt_decoder.py
edx_rest_framework_extensions/middleware.py
edx_rest_framework_extensions/permissions.py
edx_rest_framework_extensions/tests/test_jwt_decoder.py
edx_rest_framework_extensions/tests/test_middleware.py
edx_rest_framework_extensions/tests/test_permissions.py

In addition to minor improvements, this PR does the following:
- Adds a design pattern for centrally managing token versions and updates in jwt_decoder.py via `JwtTokenVersion` and `_upgrade_token`.
- Updates the `EnsureJWTAuthSettingsMiddleware` so it no longer adds `required_scopes` to Views.
Instead, the `JwtHasScope` Permission will fail if the view doesn't have `required_scopes`.
- Adds a `JwtHasUserFilterForRequestedUser` Permission to verify the `user:me` filter.
- Adds a `JWT_RESTRICTED_APPLICATION_OR_USER_ACCESS` Permission constant that encapsulates checking for Jwt related permissions for APIs that have course-related and user-related data.

Update Permissions and JWT handling for OAuth Scopes

---

edx_rest_framework_extensions/middleware.py

This should clear up a lot of noise in the logs. (There are probably many more RemoveInDjango20Warnings to fix, elsewhere.)
@robrap

Avoids a common RemovedInDjango20Warning

---

edx_rest_framework_extensions/__init__.py
edx_rest_framework_extensions/auth/jwt/middleware.py
edx_rest_framework_extensions/middleware.py

1. Add a note for JwtAuthCookieMiddleware usage.
2. Remove unused import missed in earlier clean-up.
ARCH-262
FYI: It is not important to get this deployed, but just wanted to complete this update.

ARCH-262: Minor clean-up of authn.

---

edx_rest_framework_extensions/auth/jwt/decoder.py

Temporarily, ecommerce is delegating to this jwt_decode_handler, with
its own fallback to allow for multiple issuers. Logging suppression is
required until ecommerce is down to a single issuer and can use this
jwt_decode_handler directly.  Ecommerce needs to suppress logging
because the exceptions for BadSignature are invalid due to the fallback
decoder that can in fact properly decode the token.
Note: this should be reverted as part of ARCH-276.
ARCH-283
FYI: The version was already updated to 2.0.2 in a past PR but not yet released.

ARCH-283: Enhance exception message for jwt_decode_handler.

---

README.rst
edx_rest_framework_extensions/__init__.py
edx_rest_framework_extensions/middleware.py
edx_rest_framework_extensions/tests/test_middleware.py

see other PR for moving from edx-django-utils: https://github.com/edx/edx-django-utils/pull/18  
https://openedx.atlassian.net/browse/REVMI-35  
This is the approach @robrap recommended in the openedx slack architecture room.  
Also, I'm not sure how I would test this locally, so any tips would be appreciated!

add request_user_id metric to new relic from middleware.py

---

AUTHORS
edx_rest_framework_extensions/__init__.py
edx_rest_framework_extensions/auth/jwt/cookies.py
edx_rest_framework_extensions/auth/jwt/tests/test_cookies.py

This PR updates the logic of `edx_rest_framework_extensions.auth.jwt.cookies.get_decoded_jwt` so that jwt cookie is queried in `request.auth` if not found in `request.COOKIES`.

ENT-1783: Update cookies.get_decoded_jwt logic to also query jwt cookie from request.auth

---

edx_rest_framework_extensions/__init__.py
edx_rest_framework_extensions/auth/jwt/cookies.py
edx_rest_framework_extensions/auth/jwt/tests/test_cookies.py

This is a revert PR for https://github.com/edx/edx-drf-extensions/pull/69 for details see https://github.com/edx/edx-drf-extensions/pull/69#discussion_r286244610

ENT-1783: Revert 'Update cookies.get_decoded_jwt logic to also query jwt cookiefrom request.auth'

---

edx_rest_framework_extensions/__init__.py
edx_rest_framework_extensions/auth/jwt/authentication.py
edx_rest_framework_extensions/auth/jwt/tests/test_authentication.py

This PR adds a helper method in `edx_rest_framework_extensions/auth/jwt/authentication.py` to get decoded hwt token from `request.auth`

ENT-1783: Added a helper method to get jwt token from request.auth

---

edx_rest_framework_extensions/__init__.py
edx_rest_framework_extensions/auth/jwt/authentication.py

This should fix the errors we saw when the latest upgrade of this package went to prod.
```
exceptions:AttributeError: 'WSGIRequest' object has no attribute 'successful_authenticator'
Traceback (most recent call last):
File "/edx/app/edxapp/venvs/edxapp/bin/gunicorn", line 11, in <module>
File "/edx/app/edxapp/venvs/edxapp/local/lib/python2.7/site-packages/gunicorn/app/wsgiapp.py", line 74, in run
File "/edx/app/edxapp/venvs/edxapp/local/lib/python2.7/site-packages/gunicorn/app/base.py", line 192, in run
File "/edx/app/edxapp/venvs/edxapp/local/lib/python2.7/site-packages/gunicorn/app/base.py", line 72, in run
File "/edx/app/edxapp/venvs/edxapp/local/lib/python2.7/site-packages/gunicorn/arbiter.py", line 185, in run
File "/edx/app/edxapp/venvs/edxapp/local/lib/python2.7/site-packages/gunic …
```

Fix call to is_jwt_authenticated when the request has no successful_authenticator attribute

---

README.rst
edx_rest_framework_extensions/auth/jwt/middleware.py
edx_rest_framework_extensions/middleware.py

Django >=1.10 uses a slightly different middleware framework. Using the old framework results in RemovedInDjango20 warnings. Django provides MiddlewareMixin for classes that work as both old-style and new-style middlewares. Inheriting from it allows clients of this library to move to the new middleware framwork and silence the deprecation warnings.

Add MiddlewareMixin to all middleware classes

---

edx_rest_framework_extensions/__init__.py
edx_rest_framework_extensions/auth/jwt/middleware.py
edx_rest_framework_extensions/auth/jwt/tests/test_middleware.py
edx_rest_framework_extensions/middleware.py
edx_rest_framework_extensions/permissions.py
tox.ini

Middleware enables DRF JwtAuthentication authentication class for
endpoints using the new LoginRequired permission class.
Enables a non-standard use of DRF, because DRF only supports returning
a 401 for unauthorized users, but this middleware allows a DRF endpoint
to redirect to login.
This can be used to convert a plain Django view which was using
@login_required into a DRF APIView, which is useful to enable our DRF
JwtAuthentication authentication class.
NOTE: This includes a breaking change that is unlikely to affect anyone
unless they subclassed `JwtAuthCookieMiddleware`, which switched from
using `process_request` to `process_view` so it would not run before
this new middleware.
ARCH-1051
The ecommerce PR that makes use of this middleware can be found here: …

ARCH-1051: enables this to work with jwt auth login required middleware

---

edx_rest_framework_extensions/__init__.py
edx_rest_framework_extensions/auth/jwt/middleware.py
edx_rest_framework_extensions/auth/jwt/tests/test_middleware.py

JWT cookie authentication uses DRF, which does not set `request.user`
until the Middleware call: `process_response`.  This change sets the
`request.user` in process_view, which happens after all
`process_request` calls.
This is has been added to the existing `JwtAuthCookieMiddleware`.
ARCH-1197

ARCH-1197: request.user set in JwtAuthCookieMiddleware

---

edx_rest_framework_extensions/__init__.py
edx_rest_framework_extensions/auth/jwt/middleware.py
edx_rest_framework_extensions/auth/jwt/tests/test_middleware.py
edx_rest_framework_extensions/config.py
edx_rest_framework_extensions/permissions.py
edx_rest_framework_extensions/settings.py

Although setting the `request.user` during `process_view` worked to
solve ARCH-1197 in ecommerce, it introduced an OOM bug in edx-platform.
This introduces a temporary toggle using a Django Setting so that the
fix can remain in ecommerce without affecting other IDAs like
edx-platform.
Once ARCH-1199 is complete and the issue is fixed, it is expected that
this toggle will be removed.
ARCH-1210
**UPDATE:** The second commit refactors from a Waffle Switch to a Django Setting so that we are not blocked by Devops, since we don't have access to Ecommerce Admin in Production.  It also better allows me to check that the solution sticks for ecommerce.

ARCH-1210: Add toggle to determine whether to set request.user.

---

README.rst
csrf/api/v1/views.py
csrf/tests/test_api.py
edx_rest_framework_extensions/__init__.py
edx_rest_framework_extensions/auth/jwt/authentication.py
edx_rest_framework_extensions/auth/jwt/constants.py
edx_rest_framework_extensions/auth/jwt/middleware.py
edx_rest_framework_extensions/auth/jwt/tests/test_authentication.py
edx_rest_framework_extensions/auth/jwt/tests/test_middleware.py
edx_rest_framework_extensions/config.py
edx_rest_framework_extensions/settings.py
tox.ini

**remove jwt authentication from csrf endpoint**
The main purpose of this commit is to remove the IsAuthenticated
permission from the /csrf/api/v1/token endpoint. The permission was
never needed, and doesn't allow the endpoint to be used to retrieve a
csrf token for use with an anonymous POST.
A temporary Django Setting was added to help with the roll-out:
- EDX_DRF_EXTENSIONS[ENABLE_ANONYMOUS_ACCESS_ROLLOUT]
This setting will help manage the rollout of CSRF protection.
Other minor fixes included:
- Updated README to clarify the purpose of the repo.
- Added testing of the existing csrf app to tox.
ARCH-1269

ARCH-1269: remove jwt authentication from csrf endpoint 

---

edx_rest_framework_extensions/__init__.py
edx_rest_framework_extensions/auth/jwt/cookies.py
edx_rest_framework_extensions/auth/jwt/tests/test_cookies.py

The login_refresh endpoint in the LMS was updated to be based on the
user's session, rather than requiring an additional refresh cookie, so
removing any references to the unused refresh cookie and
JWT_AUTH_REFRESH_COOKIE setting.
https://openedx.atlassian.net/browse/ARCH-418

ARCH-418: Remove jwt_refresh_cookie

---

csrf/api/v1/views.py
csrf/tests/test_api.py
edx_rest_framework_extensions/__init__.py
edx_rest_framework_extensions/config.py
edx_rest_framework_extensions/permissions.py

- restore public api toggle constants
- add permission of AllowAny to the csrf endpoint
The toggle constants for oauth scopes are used outside of
edx-drf-extensions (in edx-platform), so these constants must survive
and stay separate. NOTE: This problem was introduced in 2.4.2 while
edx-platform remained on 2.4.0. This will be fixed in edx-platform
while upgrading.
This fixes a csrf endpoint bug introduced into the 2.4.3 release,
where an IDA that had a default permission of DjangoModelPermissions
would start failing on this endpoint.
ARCH-1269

ARCH-1269: minor fixes to recent releases

---

Makefile
edx_rest_framework_extensions/tests/test_paginators.py
requirements/dev.txt
requirements/docs.txt
requirements/test.in
requirements/test.txt
setup.cfg
test_settings.py
tox.ini

While working on https://github.com/edx/edx-drf-extensions/pull/91, I got frustrated with the poor error messages and weaker CLI of nose as compared to pytest.
#99 moves us to pytest anyway, but I'm not sure when it will merge, so this PR pulls out the nose-to-pytest-specific changes so that they can merge on their own.
cc @Ayub-Khan , @jmbowman , @nedbat

Switch from nose to pytest

---

manage.py

@jinder1s This should fix the `ImportError: No module named 'test_settings'` thing that happens when you try to invoke `pytest` directly.
This is just a copypasta from another edX library.

Add basic manage.py file to allow direct pytest usage

---

edx_rest_framework_extensions/__init__.py
edx_rest_framework_extensions/config.py
edx_rest_framework_extensions/permissions.py
edx_rest_framework_extensions/tests/test_permissions.py

The oauth2.enforce_jwt_scopes waffle switch was added temporarily for
the rollout of JWT scopes. This removes the toggle and replaces it with
logic equivalent to setting `oauth2.enforce_jwt_scopes` to True.
BREAKING CHANGE:
This removes a toggle that may or may not have been set in any
particular environment, and was defaulted to False.
Before taking this upgrade:
* Make sure your IDA includes `EnsureJWTAuthSettingsMiddleware` in its
declared `MIDDLEWARE` or `MIDDLEWARE_CLASSES`.
* Although you could first check and/or set the
`oauth2.enforce_jwt_scopes` waffle switch to True in all environments
for your IDA, this upgrade is unlikely to cause an issue. If you want to
play it safe, setting the switch first is how you do it, but then you
need remove the switch.
After taking this upgrade:
* …

BOM-1324: remove oauth2.enforce_jwt_scopes toggle

---

edx_rest_framework_extensions/auth/jwt/authentication.py
edx_rest_framework_extensions/auth/jwt/tests/test_authentication.py
edx_rest_framework_extensions/config.py
edx_rest_framework_extensions/settings.py

ENABLE_ANONYMOUS_ACCESS_ROLLOUT flag was a temporarily used to facilitate rollout
of CSFR protection for MFEs. With that effort finished, the flag is no longer necessary
and is now being removed.

BOM-1098 Removing ENABLE_ANONYMOUS_ACCESS_ROLLOUT flag

---

edx_rest_framework_extensions/__init__.py
edx_rest_framework_extensions/auth/jwt/authentication.py
edx_rest_framework_extensions/auth/jwt/cookies.py
edx_rest_framework_extensions/auth/jwt/decoder.py
edx_rest_framework_extensions/auth/jwt/tests/test_decoder.py

In 3.0.0, the switch `oauth2.enforce_jwt_scopes` was removed, which
starts checking is_restricted in JWTs. This works fine for JWTs created
with the LMS, but uncovered a pre-existing bug that will only show
itself in the Ecommerce Service for certain JWTs which were meant to be
decoded with a custom jwt_decode_handler. In the Ecommerce Service only,
this custom jwt_decode_handler is set using the JWT_DECODE_HANDLER
setting.
This fix updates the JWT code to respect the JWT_DECODE_HANDLER setting
of JWT_AUTH, and uses the configured handler rather than assuming the
edx-drf-extensions version will always be used.
ARCHBOM-1036

ARCHBOM-1036: fix for edx-drf-extensions 3.0.0

---

.travis.yml
edx_rest_framework_extensions/__init__.py

5.0.0 is the same release as 4.0.4. It is being released as its own
major version, because 4.0.1 had BREAKING CHANGES and should have been
its own release. This 5.0.0 version is simply being used to call
attention to the BREAKING CHANGES in 4.0.1.
NOTE: We will probably not go through the effort of releasing 4.0.5
to revert back to 4.0.0.
Additionally, the travis config was breaking on tagged releases because
it was trying to deploy twice. This should also fix that problem.

release 4.0.4 as 5.0.0

---

edx_rest_framework_extensions/__init__.py
edx_rest_framework_extensions/middleware.py
edx_rest_framework_extensions/tests/test_middleware.py

BREAKING CHANGE: Changed names of NewRelic metric names and values.
Has potential to break NewRelic dashboards or alerts, but should not
have an affect on deployed code.
- Renamed 'request_auth_type' to 'request_auth_type_guess'. This makes
it more clear that this metric could be wrong in certain cases.
- Renamed value `session-or-unknown` to `session-or-other`. This name
makes it more clear that it is the method of authentication that is in
question, not whether or not the user is authenticated.
- Added 'jwt-cookie' as new value for 'request_auth_type_guess'.
- Added new 'request_authenticated_user_found_in_middleware' metric.
Helps identify for what middleware step the request user was set, if
it was set. Example values: 'process_request', 'process_view',
'process_response', or …

ARCHBOM-128: enhance authentication metrics

---

edx_rest_framework_extensions/__init__.py
edx_rest_framework_extensions/middleware.py
edx_rest_framework_extensions/tests/test_middleware.py

The request metric request_authenticated_user_found_in_middleware was
not getting reset for each request. This fixes the issue by using the
request cache.
ARCHBOM-128

ARCHBOM-128 fix request_authenticated_user_found_in_middleware bug

---

.github/PULL_REQUEST_TEMPLATE.md
CHANGELOG.rst
README.rst
docs/changelog.rst
docs/decisions/0001-use-changelog.rst
docs/index.rst

ARCHBOM-1213
Post-merge:
* Should point to CHANGELOG.rst and ADR and clarify that Github Releases should no longer be used. Could point to the README.rst for publishing instructions.

ARCHBOM-1213: add changelog to edx-drf-extensions

---

CHANGELOG.rst
edx_rest_framework_extensions/__init__.py
requirements/base.in
requirements/base.txt
requirements/dev.txt
requirements/docs.txt
requirements/pip-tools.txt
requirements/test.txt

Unpinning drf-jwt now that
https://github.com/Styria-Digital/django-rest-framework-jwt/issues/40 is
resolved.
Bump the minor version beacuse the update to drf-jwt brings in new
blacklist functionality.
Describe in a couple of sentences what this PR adds
**Reviewers:**
finished.

ARCHBOM-1293 Upstream drf-jwt issue should be fixed.

---

CHANGELOG.rst
edx_rest_framework_extensions/__init__.py
edx_rest_framework_extensions/auth/jwt/authentication.py
edx_rest_framework_extensions/auth/jwt/tests/test_authentication.py

https://openedx.atlassian.net/browse/BOM-1845
https://github.com/Styria-Digital/django-rest-framework-jwt/pull/27/files#diff-bc0105dbb10d8b2bcacf8d191d5d0195R105
This change is causing issue. Previously it returns None but now it throws exception.
@awais786  have created a PR there https://github.com/Styria-Digital/django-rest-framework-jwt/pull/65

WIP: return None on NotAuthenticated

---

.github/PULL_REQUEST_TEMPLATE.md
CHANGELOG.rst
edx_rest_framework_extensions/__init__.py
edx_rest_framework_extensions/auth/jwt/middleware.py
edx_rest_framework_extensions/auth/jwt/tests/test_middleware.py

Adds the applications default parsers to the JWT middleware.
When a user was authenticating with a service for the first time, the
middleware was throwing an execption because it couldn't parse the
request. This was because the Request was not given any default parsers
which caused the request to fail on any/all "Content-Type"s.
Example stack trace from before this PR:
```
Traceback (most recent call last):
File "/usr/local/lib/python3.6/dist-packages/edx_rest_framework_extensions/auth/jwt/middleware.py", line 257, in _get_user_from_jwt
if jwt_authentication_class:
File "/usr/local/lib/python3.6/dist-packages/edx_rest_framework_extensions/auth/jwt/authentication.py", line 80, in authenticate
self.enforce_csrf(request)
File …
```

Add default parsers to JWT middleware

---

CHANGELOG.rst
edx_rest_framework_extensions/__init__.py
edx_rest_framework_extensions/auth/bearer/authentication.py
edx_rest_framework_extensions/auth/jwt/middleware.py
edx_rest_framework_extensions/auth/jwt/tests/test_middleware.py
edx_rest_framework_extensions/middleware.py
edx_rest_framework_extensions/tests/test_middleware.py
requirements/base.in
requirements/base.txt
requirements/dev.txt
requirements/docs.txt
requirements/pip-tools.txt
requirements/test.txt

Rename of "custom metric" to "custom attribute" was based
on a decision (ADR) captured in edx-django-utils:
https://github.com/edx/edx-django-utils/blob/master/edx_django_utils/monitoring/docs/decisions/0002-custom-monitoring-language.rst
Deprecated RequestMetricsMiddleware due to rename.  Use
RequestCustomAttributesMiddleware instead.
**JIRA:**
[ARCHBOM-1495](https://openedx.atlassian.net/browse/ARCHBOM-1495)
**Testing:**
Note: I tested locally in edx-platform with both the deprecated name and new name.  The [PR to rename in edx-platform ](https://github.com/edx/edx-platform/pull/25082) will be failing until this version has been released and edx-platform has been updated.
finished.

ARCHBOM-1495: rename custom metric to custom attribute

---

CHANGELOG.rst
edx_rest_framework_extensions/__init__.py
edx_rest_framework_extensions/auth/jwt/authentication.py
edx_rest_framework_extensions/auth/jwt/tests/test_authentication.py
edx_rest_framework_extensions/config.py

While working on ARCHBOM-1218 in https://github.com/edx/edx-drf-extensions/pull/129, I realized that some cleanup and monitoring could be moved into a separate PR (a.k.a. this PR) to make the future changes more clear and less risky.
* feat: add jwt_auth_failed custom attribute
Adds a jwt_auth_failed custom attribute that can be used for debugging,
but also will help with some planned cleanup and refactoring in
ARCHBOM-1218.
* fix: update toggle annotations 
* refactor: remove check for non-jwt tokens
At one point, drf-jwt had an issue introduced where it was raising an
error instead of returning None for non-jwt tokens, for example, bearer
tokens. A check was temporarily added to JwtAuthentication to ensure
that we continued to return None.
Since then, our team got a …

ARCHBOM-1218: jwt auth monitoring

---

Makefile
requirements/base.txt
requirements/common_constraints.txt
requirements/constraints.txt
requirements/dev.txt
requirements/pip-tools.txt
requirements/test.txt

Implemented common-constraint local sync. It gives us more control in case of different version implementation.
pip-tools gives error if two different versions of same package appears in make upgrade job. To fix this problem, added common constraint locally. It will always sync with web-url. With this approach this issue can be resolve.

build: Implemented common-constraint local sync.

---

CHANGELOG.rst
edx_rest_framework_extensions/__init__.py
edx_rest_framework_extensions/auth/jwt/decoder.py
edx_rest_framework_extensions/auth/jwt/tests/test_decoder.py
edx_rest_framework_extensions/auth/jwt/tests/utils.py
requirements/base.in
requirements/base.txt
requirements/common_constraints.txt
requirements/constraints.txt
requirements/dev.txt
requirements/test.txt

This PR constains major changes.
---------------------------
* **BREAKING CHANGE:** ``generate_jwt_token``: Now returns string (instead of bytes), and no longer requires decoding. This was to keep consistent with change to ``jwt.encode`` in `pyjwt` upgrade (see below).
* **BREAKING CHANGE:** Upgraded dependency ``pyjwt[crypto]`` to 2.1.0, which introduces its own breaking changes that may affect consumers of this library. Pay careful attention to the 2.0.0 breaking changes documented in https://pyjwt.readthedocs.io/en/stable/changelog.html#v2-0-0.
---------------------------
https://openedx.atlassian.net/browse/BOM-2470
https://pyjwt.readthedocs.io/en/stable/changelog.html#v2-0-0
This PR is fixing two issues.
Issue 1.  decode method was throwing following error.
```
decoded_token = …
```

feat: Latest pyjwt version has breaking changes and was causing tests failures. 

---

CHANGELOG.rst
edx_rest_framework_extensions/__init__.py
edx_rest_framework_extensions/auth/jwt/decoder.py
edx_rest_framework_extensions/auth/jwt/tests/test_decoder.py

Removed dropped ``require_exp`` and ``require_iat`` options from jwt.decode and instead used ``require`` option with both ``exp`` and ``iat``. For more info visit this: https://pyjwt.readthedocs.io/en/stable/changelog.html#dropped-deprecated-require-options-in-jwt-decode
**JIRA:**
[BOM-2470](https://openedx.atlassian.net/browse/BOM-2470)
**Reviewers:**
finished.

fix: replace dropped require_exp and require_iat with require option

---

CHANGELOG.rst
docs/index.rst
edx_rest_framework_extensions/__init__.py
edx_rest_framework_extensions/auth/jwt/middleware.py
edx_rest_framework_extensions/auth/jwt/tests/test_middleware.py
edx_rest_framework_extensions/permissions.py
requirements/base.in
requirements/base.txt
requirements/dev.txt
requirements/test.txt

Currently rest_condition is used to compose permission classes, however support
for composition is now part of DRF since v3.9 and rest_condition has not seen
updates in a while.
This change adds support for DRF-style composition to the middleware.
https://github.com/edx/upgrades/issues/2
**Reviewers:**
finished.

feat!: Add support for permissions composed using DRF

---

CHANGELOG.rst
edx_rest_framework_extensions/config.py

Rename toggle_warnings to toggle_warning for consistency with setting_warning.
Relates to: https://github.com/openedx/code-annotations/pull/80

FC-0001: rename toggle_warnings to toggle_warning

---

edx_rest_framework_extensions/paginators.py

When this code was extracted from edx-platform,
it was likely used to paginate search results
specifically from the "edx-search" library
(http://github.com/openedx/edx-search/).
Now that this is generic utility function,
it makes more sense to just say
"search results" instead of
"edx-search results", as the
result list can come from any backend.
@georgebabey , as the original author, do you mind reviewing this docs tweak?

docs: generalize "edx-search" to "search" in pagination docstring

---

CHANGELOG.rst
edx_rest_framework_extensions/__init__.py
edx_rest_framework_extensions/auth/jwt/authentication.py
edx_rest_framework_extensions/auth/jwt/decoder.py
edx_rest_framework_extensions/auth/jwt/tests/test_decoder.py
edx_rest_framework_extensions/auth/jwt/tests/utils.py
test_settings.py

Raise exception decoding symmetric jwt if decode_symmetric_token is false
By default jwt_decode_handler will decode symmetric tokens but if we pass decode_symmetric_token as False,
it will raise InvalidTokenError with NoSuitableSigningKeys in __cause__ attr of the exxception. Caller can determine whether the
exception was because of NoSuitableSigningKeys or something else went wrong.
**JIRA:**
[LEARNER-8941](https://2u-internal.atlassian.net/browse/LEARNER-8941)
* **Dependencies:**: None.
**Reviewers:**
finished.

feat: Raise exception decoding symmetric jwt if flag is false

---

edx_rest_framework_extensions/__init__.py
edx_rest_framework_extensions/auth/jwt/authentication.py
edx_rest_framework_extensions/auth/jwt/tests/test_authentication.py

If user has been disabled by admin, JWT Token Authentication should fail with appropriate message.
Disabled user refers to user's password being set as unusable by admin on page `/support/manage_user`
**JIRA:**
[LEARNER-9001](https://2u-internal.atlassian.net/browse/LEARNER-9001)
* **Dependencies:**: None
* **Merge deadline:** August 19th 2022
* **Author concerns:** None
**Testing instructions:**
* Fetch JWT token for an edx user.
* Call the api `/api/mobile/v1/users/honor/course_enrollments/` with the JWT token.
* See that response is received.
* Disable the user from the page `/support/manage_user`.
* Call api again with same user.
* Observe authentication failed error `User disabled by admin: <username>`
**Reviewers:**
- [@jawad-khan  ] tag …

feat: Error message when JWT user disabled

---

CHANGELOG.rst
edx_rest_framework_extensions/__init__.py
edx_rest_framework_extensions/auth/jwt/authentication.py
edx_rest_framework_extensions/auth/jwt/tests/test_authentication.py

This reverts commit d483e6651b584ff787bc9678dc5237264145c281.
There were unintended consequences (errors) for checking disabled user in JwtAuthentication.
**Reviewers:**
finished.

Revert "feat: Error message when JWT user disabled (#268)"

---

CHANGELOG.rst
edx_rest_framework_extensions/__init__.py
edx_rest_framework_extensions/middleware.py
edx_rest_framework_extensions/tests/test_middleware.py

Added custom attribute enduser.id, following OpenTelemetry convention. The old custom attribute request_user_id should be considered deprecated. This works with some New Relic automatic tooling around users. See https://docs.newrelic.com/docs/errors-inbox/error-users-impacted/
Task: https://github.com/edx/edx-arch-experiments/issues/140
finished.

feat: add enduser.id custom attribute for monitoring

---

requirements/base.txt
requirements/constraints.txt
requirements/dev.txt
requirements/docs.in
requirements/docs.txt
requirements/pip.txt
requirements/test.txt

- `Sphinx>5.3.0` requires `docutils>=0.18,<0.20` but `sphinx_rtd_theme` which needs `docutils<0.18` is causing make upgrade job to fail due to conflicts.
- Pinned the `Sphinx` version unless sphinx_rtd_theme>=1.1.1 is available on PyPI

fix: pin sphinx version

---

CHANGELOG.rst
edx_rest_framework_extensions/__init__.py
edx_rest_framework_extensions/auth/jwt/authentication.py
edx_rest_framework_extensions/auth/jwt/tests/test_authentication.py

The Enterprise Titans squad is investigating an issue with license-manager where it is intermittently throwing a 401 with a `AuthenticatedFailed('User retrieval failed.')` message that has proved difficult to debug thus far.
The impact is that users are intermittently unable to retrieve their subscription plans/licenses/etc., leading to a degraded and poor experience. 
Something within the JWT authentication's middleware is throwing an exception in `authenticate_credentials`, seemingly related to opening a database connection based on Splunk logs.
We are hoping to add additional logs should they be helpful for further debugging.
**JIRA:**
TBD
* **Dependencies:**: List dependencies on other outstanding PRs, issues, etc.
* **Merge deadline:** List …

chore: add additional logging to JWT auth middleware authenticate_credentials

---

CHANGELOG.rst
edx_rest_framework_extensions/__init__.py
edx_rest_framework_extensions/auth/jwt/decoder.py
edx_rest_framework_extensions/auth/jwt/tests/test_decoder.py

Part of https://github.com/edx/edx-arch-experiments/issues/261

feat: Add JWT key-set size custom attribute to aid in key rotations

---

CHANGELOG.rst
edx_rest_framework_extensions/__init__.py

Tags for 8.5.1 and 8.5.2 failed earlier, so
this uses the fresh version of 8.5.3 to test
the fixed packaging.
finished.

fix: bump to 8.5.3

---

CHANGELOG.rst
edx_rest_framework_extensions/auth/jwt/decoder.py
edx_rest_framework_extensions/auth/jwt/tests/test_decoder.py

Add new custom attributes to verify how the issuer is being verified at this time.
finished.

feat: add issuer monitoring

---

CHANGELOG.rst
edx_rest_framework_extensions/__init__.py
edx_rest_framework_extensions/middleware.py
edx_rest_framework_extensions/tests/test_middleware.py

Add edx_drf_extensions_version custom attribute to help monitor rollout of upgrades to this library.
Requires use of RequestCustomAttributesMiddleware. Versions before 8.7.0 will not include this attribute, but should include `request_auth_type_guess`.
finished.

feat: add edx_drf_extensions_version custom attribute

---

CHANGELOG.rst
edx_rest_framework_extensions/__init__.py
edx_rest_framework_extensions/auth/jwt/authentication.py

chore: Fix RemovedInDjango40Warning for middleware get_response

---

CHANGELOG.rst
edx_rest_framework_extensions/__init__.py
edx_rest_framework_extensions/auth/jwt/authentication.py
edx_rest_framework_extensions/auth/jwt/tests/test_authentication.py

Fixes exceptional case where JwtAuthentication should not CSRF protect a request that has both a JWT token in the authorization header and a JWT cookie, since the cookie should be ignored.
Note: I had minor concerns that Mobile could have issues here, and I just didn't want to have that concern, so I took care of the exceptional case.
finished.

fix: exceptional case with JwtAuthentication

---

CHANGELOG.rst
edx_rest_framework_extensions/__init__.py
edx_rest_framework_extensions/auth/jwt/authentication.py
edx_rest_framework_extensions/auth/jwt/tests/test_authentication.py

The default exception that comes from the JSONWebTokenAuthentication
does not have enough information about why the JWT auth failed in the
exception that it propagates.  However, we can get this information by
looking at the PyJWT exception that was thrown so we added some tooling
to get that lower level exception if it exists.

fix: Add more monitoring to the JWT Auth Class.

---

CHANGELOG.rst
edx_rest_framework_extensions/auth/jwt/decoder.py

**Related ticket**
- https://github.com/openedx/edx-drf-extensions/issues/290
**Related PR**
- https://github.com/openedx/edx-platform/pull/32270
**Tasks**

feat: make jwt decode fucntion generic

---

CHANGELOG.rst
edx_rest_framework_extensions/__init__.py
edx_rest_framework_extensions/auth/jwt/authentication.py
edx_rest_framework_extensions/auth/jwt/decoder.py
edx_rest_framework_extensions/auth/jwt/tests/test_authentication.py
edx_rest_framework_extensions/auth/jwt/tests/test_decoder.py
edx_rest_framework_extensions/auth/jwt/tests/utils.py
edx_rest_framework_extensions/config.py
edx_rest_framework_extensions/settings.py
test_settings.py

Adds toggle
EDX_DRF_EXTENSIONS[ENABLE_JWT_VS_SESSION_USER_MONITORING]
to enable the following features:
- New custom attributes is_jwt_vs_session_user_check_enabled,
jwt_auth_session_user_id, jwt_auth_and_session_user_mismatch,
and invalid_jwt_cookie_user_id for monitoring and debugging.
- When forgiving JWT cookies are also enabled, user mismatches
will now result in a failure, rather than a forgiving JWT.
This implements https://github.com/openedx/edx-drf-extensions/issues/381#issuecomment-1729755383.
finished.

feat: handle jwt cookie vs session user mismatch 

---

CHANGELOG.rst
edx_rest_framework_extensions/__init__.py
edx_rest_framework_extensions/auth/jwt/authentication.py
edx_rest_framework_extensions/auth/jwt/tests/test_authentication.py

Made changes to the recent ENABLE_JWT_VS_SESSION_USER_CHECK custom attributes. Although this is technically a breaking change, skipping major release because of limited use of these attributes.
- The jwt_auth_session_user_id attribute has been renamed to clarify that this attribute only appears in the case of a mismatch.
- Dropped jwt_auth_and_session_user_mismatch, which is redundant to simply checking for the existence of jwt_auth_mismatch_session_user_id.
- Updated annotations for jwt_auth_request_user_not_found, because it has proven to be a real case in Production and not just in testing.
finished.

feat! updated jwt vs session user monitoring

---

CHANGELOG.rst

A small backward incompatible change was found in the updated test utility method generate_unversioned_payload. The user argument now requires an id attribute. The changelog has been updated to reflect this.

docs: update CHANGELOG.rst for 8.11.0

---

CHANGELOG.rst
docs/decisions/0002-remove-use-jwt-cookie-header.rst
edx_rest_framework_extensions/__init__.py
edx_rest_framework_extensions/auth/jwt/authentication.py
edx_rest_framework_extensions/auth/jwt/middleware.py
edx_rest_framework_extensions/auth/jwt/tests/test_authentication.py
edx_rest_framework_extensions/auth/jwt/tests/test_middleware.py
edx_rest_framework_extensions/config.py
edx_rest_framework_extensions/settings.py

An issue was found when both ENABLE_JWT_VS_SESSION_USER_CHECK and ENABLE_SET_REQUEST_USER_FOR_JWT_COOKIE were enabled at the same time in an ecommerce stage environment for edx.org, that is not reproducible locally. Additionally, the issue killed the requests without providing errors, so potentially caused an infinite loop or some such issue.
The guess is that the code for setting the user behind ENABLE_SET_REQUEST_USER_FOR_JWT_COOKIE, and the code to get the user in the new ENABLE_JWT_VS_SESSION_USER_CHECK check, were somehow in conflict. This update attempts to skip the JWT vs Session check in the case that we have set the user based on the JWT, in which case it would be a JWT vs JWT check, which not only is unnecessary, but also may be the cause of the issue.
Adds …

fix: update jwt vs session user monitoring

---

CHANGELOG.rst
edx_rest_framework_extensions/__init__.py
edx_rest_framework_extensions/auth/jwt/authentication.py
edx_rest_framework_extensions/auth/jwt/tests/test_authentication.py

Fixed bug where JwtAuthentication called with a Django request instead of a DRF request would fail. Also added custom attribute jwt_auth_request_user_not_found to track down these unexpected cases.
finished.

fix: JwtAuthentication with Django request

---

CHANGELOG.rst
edx_rest_framework_extensions/__init__.py
edx_rest_framework_extensions/auth/jwt/authentication.py
edx_rest_framework_extensions/auth/jwt/tests/test_authentication.py
edx_rest_framework_extensions/config.py
edx_rest_framework_extensions/settings.py

Fixes a bug for any service other than the identity service
(LMS/CMS), where the session's local service user id would never
match the JWT LMS user id when compared.
- The custom attribute jwt_auth_mismatch_session_lms_user_id was
renamed to jwt_auth_mismatch_session_lms_user_id to make this more
clear.
- The setting EDX_DRF_EXTENSIONS[VERIFY_LMS_USER_ID_PROPERTY_NAME]
was added to enable choosing the user object property that contains
the LMS user id, if one exists. If this is set to None (the
default), the check will use the lms_user_id property if it is
found, and otherwise will skip this additional protection. In case
of an unforeseen issue, use 'skip-check' to skip the check, even
when there is an lms_user_id property.
- The custom attribute …

fix!: bug in JWT vs session user id compare

---

CHANGELOG.rst

The wrong name for a custom attribute was used
when referring to a name change in the CHANGELOG.

fix: CHANGELOG entry typo

---

.readthedocs.yml
CHANGELOG.rst
edx_rest_framework_extensions/__init__.py
edx_rest_framework_extensions/auth/jwt/authentication.py
edx_rest_framework_extensions/auth/jwt/tests/test_authentication.py

- Fixed bug for successful JWTs where the JWT user id was still
using the service user id, rather than the LMS user id, so comparison
against the LMS user id would fail.
- As part of the bug fix, the custom attribute
``failed_jwt_cookie_user_id`` was renamed to
``jwt_cookie_lms_user_id``, and will be set for all JWT cookies.
Since this is only a breaking change for recently added monitoring,
this won't be versioned as a breaking change.
This is part of:
https://github.com/edx/edx-arch-experiments/issues/429
finished.

fix: bug with service user id vs lms user id

---

.readthedocs.yaml
docs/authentication.rst
docs/decisions/index.rst
docs/index.rst
edx_rest_framework_extensions/middleware.py

Following cookiecutter recommendations in this update: https://github.com/openedx/edx-drf-extensions/commit/bb2b78347d96145d56e5a3b671ad36e604be612e
- Rename .readthedocs.yml to .readthedocs.yaml
- Remove extra python install lines from edx-platform
- Add fail_on_warning to protect against doc issues

docs: update .readthedocs.yaml

---

CHANGELOG.rst
edx_rest_framework_extensions/__init__.py
edx_rest_framework_extensions/auth/jwt/authentication.py
edx_rest_framework_extensions/auth/jwt/tests/test_authentication.py
edx_rest_framework_extensions/config.py
edx_rest_framework_extensions/settings.py

Simplified JWT cookie vs session user check by checking username instead of lms user id.
- Removed ``VERIFY_LMS_USER_ID_PROPERTY_NAME``, which is no longer needed.
- Removed custom attribute ``jwt_auth_get_lms_user_id_status``, since we no longer attempt to get the lms_user_id from the user object.
- Renames custom attribute ``jwt_auth_mismatch_session_lms_user_id`` to ``jwt_auth_mismatch_session_username``.
- Adds custom attribute ``jwt_auth_mismatch_jwt_cookie_username``.
- Adds custom attribute ``jwt_cookie_unsafe_decode_issue`` for when a JWT cookie cannot even be unsafely decoded.
**Issue:**
https://github.com/edx/edx-arch-experiments/issues/429
finished.

feat: JWT vs session user check with username

---

CHANGELOG.rst
edx_rest_framework_extensions/__init__.py
edx_rest_framework_extensions/auth/jwt/authentication.py
edx_rest_framework_extensions/auth/jwt/tests/test_authentication.py
edx_rest_framework_extensions/config.py
edx_rest_framework_extensions/settings.py

Reverts openedx/edx-drf-extensions#422

Revert "feat: JWT vs session user check with username"

---

CHANGELOG.rst
edx_rest_framework_extensions/__init__.py
edx_rest_framework_extensions/auth/jwt/authentication.py
edx_rest_framework_extensions/auth/jwt/tests/test_authentication.py
edx_rest_framework_extensions/config.py
edx_rest_framework_extensions/settings.py

Unauthenticate in case of mismatch between JWT email and lms user email
**JIRA:**
[VAN-1694](https://openedx.atlassian.net/browse/VAN-1694)

feat: add check for enforcing jwt and lms user email match

---

CHANGELOG.rst
edx_rest_framework_extensions/__init__.py
edx_rest_framework_extensions/auth/jwt/authentication.py
edx_rest_framework_extensions/auth/jwt/tests/test_authentication.py

**Issue:** When JwtAuthentication class [raises](https://github.com/openedx/edx-drf-extensions/blob/master/edx_rest_framework_extensions/auth/jwt/authentication.py#L113-L119) `JwtUserEmailMismatchError` custom exception, it is not identified by the default exception handler of rest framework, therefore, returns `response = None` and hence we [get](https://www.django-rest-framework.org/api-guide/exceptions/#custom-exception-handling) `500 Server error`. 
**Fix:** This PR handles this issue by subclassing `JwtAuthenticationError` from the `AuthenticationFailed` exception which is a known exception and will be handled by the default exception handler.
**JIRA:**
[VAN-1694](https://openedx.atlassian.net/browse/VAN-1694)
* **Dependencies:**: List …

fix: change base class for JwtAuthenticationError
